-- Script generated by SimpleSpy - credits to exx#9394

-- Wireless cash collect
game:GetService("ReplicatedStorage").CollectCashEvent:FireServer()

-- while true do
--     wait()
--     local args = {
-- [1] = workspace.Tycoon5.SpawnedVehicles.Tank
--     }
--     game:GetService("ReplicatedStorage").FireTank:InvokeServer(unpack(args))
-- end